### PR TITLE
chnetns: Perfect forward all arguments

### PR DESCRIPTION
**Pull request by st31ny**
* source: https://stackoverflow.com/questions/4824590/propagate-all-arguments-in-a-bash-shell-script#4824637

### CODE REVIEW

**Comment by Jamesits** [comment]
@steinymity I see you have created 2 pull requests but closing them by deleting the branch. Is this intended or by mistake? Do you mind me directly rebase my master tree to contain your commits?

**Comment by st31ny** [comment]
Oh, this was by mistake... Didn't know that deleting the branch would close the Pull request. I actually did a bunch of improvements, added a tunnel service for private, isolated NICs (similar to bridge but without a bridge ;)), see https://github.com/steinymity/systemd-named-netns/commits/master. What do you think about these?

Moreover, I also packaged the whole thing for Debian, see https://github.com/steinymity/systemd-named-netns/tree/debian.

**Comment by Jamesits** [comment]
Thanks, that’s great!

Sorry I don’t have much time to look into this now since I’m in the exam week now... Will do in several days.

**Comment by Jamesits** [comment]
In other words, would you like to directly push to my repo if you have any enhancement to this project? I've invited you.

**Comment by st31ny** [comment]
Sure, thanks for the invitation :)

**Pull request closed without merging**
